#davlatlar = ["Qirg`iziston " , "Mangoliya " , "Brazilya", "Turkmaniston", "Arabiston " , "Shvetsariya "]
#print ( davlatlar)
#davlatlar.sort()
#print (davlatlar)
#print("Sanalgan davlatlar" , len(davlatlar) )
#print(sorted(davlatlar , reverse=True) )
#davlatlar.reverse()
#print(davlatlar)
#davlatlar.sort(reverse=True)
#print(davlatlar)
#davlatlar.sort()
#print(davlatlar)  
juft_sonlar = list(range(120,1200,2))
#toq_sonlar = list(range (119,1200,2))
#print(juft_sonlar)
#print("Juft sonlar yig`indisi " , sum(juft_sonlar))
#print (toq_sonlar)
#print("Toq sonlar yig`indisi " , sum(toq_sonlar))
#kata_son = max(juft_sonlar)
#kichik_son = max(toq_sonlar)
#ayirma = (kichik_son - kata_son)
#print( "Katta va kichik sonlar ayirmasi" , ayirma)
#print(len(juft_sonlar))
print("Birinchi 20 ta son" , juft_sonlar[0:21])
print("O`rtadagi 20 ta son" , juft_sonlar[259:279])
print("Oxirgi 20 ta son" , juft_sonlar[519:])